query ALL_NEWS {
  news {
    data {
      id
      attributes {
        Name
        Photo{
          data{
            attributes{
              url
            }
          }
        }
        createdAt
      }
    }
  }
}
