query ALL_PRODUCTS {
  products(pagination: { limit: 50 }) {
    data {
      id
      attributes {
        Name
        SubName
        Price
        Desc
        Photo {
          data {
            attributes {
              url
            }
          }
        }
        categories {
          data {
            id
            attributes {
              Name
            }
          }
        }
      }
    }
  }
}
