query GET_SLIDERS{
  sliders{
    data{
      attributes{
        H1
        H2
        H3
        Photo{
          data{
            attributes{
              url
            }
          }
        }
        LevitIMG{
          data{
            attributes{
              url
            }
          }
        }
        URL
      }
    }
  }
}