query ID_PRODUCT($ID: ID) {
  product(id: $ID){
    data{
      id
      attributes{
        Name
        Desc
        Price
        SubName
        Photo{
          data{
            attributes{
              url
            }
          }
        }
      }
    }
  }
}
